cafe/urls.py
from django.urls import path,include
from . import views
from django.conf import settings
from django.conf.urls.static import static
from .views import SignUpView

app_name = 'cafe'

urlpatterns = [
    path('signup/', SignUpView.as_view(), name='signup'),
    path('accounts/', include('django.contrib.auth.urls')),
    path('', views.product_list, name='product_list'),
    path('<slug:category_slug>/', views.menu_list, name='product_list_by_category'),
    path('<slug:category_slug>/', views.product_list, name='product_list_by_category'),
    path('<int:id>/<slug:slug>/', views.product_detail, name='product_detail'),
    path('', views.home, name='home'),

]

orders/urls.py
from django.urls import path
from . import views

app_name = 'orders'

urlpatterns = [
    path('create/', views.order_create, name='order_create'),
    path('admin/order/<int:order_id>/', views.admin_order_detail, name='admin_order_detail'),
    path('admin/order/<int:order_id>/pdf/', views.admin_order_pdf, name='admin_order_pdf'),
    path('myorders/<int:username_id>/', views.order_list, name='myorders'),
    path('myorders/<int:username_id>/<int:order_id>', views.order_detail, name='order_detail'),
]

studentcafe/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('cart', include('cart.urls')),
    path('payment/', include('payment.urls', namespace='payment')),
    path('', include('cafe.urls')),
    path('cafe/', include('django.contrib.auth.urls')),
    path('orders/', include('orders.urls')),
   ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

orders/models.py
from django.db import models
from cafe.models import CustomUser
import cafe.models
from cafe.models import Product


class Order(models.Model):
    username = models.ForeignKey(cafe.models.CustomUser, related_name='user', on_delete=models.CASCADE)
    first_name = models.CharField(max_length=60)
    last_name = models.CharField(max_length=60)
    email = models.EmailField()
    address = models.CharField(max_length=150)
    postal_code = models.CharField(max_length=30)
    city = models.CharField(max_length=100)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    paid = models.BooleanField(default=False)
    braintree_id = models.CharField(max_length=150, blank=True)
    class Meta:
        ordering = ('-created',)

    def __str__(self):
        return 'Order {}'.format(self.id)

    def get_total_cost(self):
        return sum(item.get_cost() for item in self.items.all())


class OrderItem(models.Model):
    order = models.ForeignKey(Order, related_name='items', on_delete=models.CASCADE)
    product = models.ForeignKey(Product, related_name='order_items', on_delete=models.CASCADE)
    price = models.DecimalField(max_digits=10, decimal_places=2)
    quantity = models.PositiveIntegerField(default=1)

    def __str__(self):
        return '{}'.format(self.id)

    def get_cost(self):
        return self.price * self.quantity

orders/forms.py
from django import forms
from .models import Order, Product, CustomUser


class OrderCreateForm(forms.ModelForm):
    class Meta:
        model = Order
        fields = ['username', 'first_name', 'last_name', 'email', 'address', 'postal_code', 'city']
        exclude = ('username',)



        # Exclude 'username field here, it will be added with current user name

orders/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.models import User
from django.urls import reverse
from django.shortcuts import render, redirect, get_object_or_404
from django.views import generic

from .models import OrderItem
from .forms import OrderCreateForm
from cafe.models import CustomUser
from cart.cart import Cart
from django.contrib.auth.decorators import login_required
from django.contrib.admin.views.decorators import staff_member_required
from .models import *
from .forms import *
from .models import Order
from cafe.models import *
from django.conf import settings
from django.http import HttpResponse
from django.template.loader import render_to_string
import weasyprint
from .tasks import order_created


@staff_member_required
def admin_order_pdf(request, order_id):
    order = get_object_or_404(Order, id=order_id)
    html = render_to_string('orders/order/pdf.html',
                            {'order': order})
    response = HttpResponse(content_type='application/pdf')
    response['Content-Disposition'] = 'filename=\
        "order_{}.pdf"'.format(order.id)
    weasyprint.HTML(string=html).write_pdf(response, stylesheets=[weasyprint.CSS('static/css/pdf.css')])
    return response


@staff_member_required
def admin_order_detail(request, order_id):
    order = get_object_or_404(Order, id=order_id)
    return render(request,
                  'admin/orders/order/detail.html',
                  {'order': order})


@login_required
def order_create(request):
    cart = Cart(request)
    order=Order(username=request.user)
    #order = Order(username=request.user, first_name=CustomUser.first_name, last_name=CustomUser.last_name, email=CustomUser.email, address=CustomUser.address, postal_code=CustomUser.zipcode, city=CustomUser.city)
    if request.method == 'POST':

        form = OrderCreateForm(request.POST, instance=order)
        if form.is_valid():
            order = form.save()
            #            order.username = CustomUser.username
            for item in cart:
                OrderItem.objects.create(
                    order=order,
                    product=item['product'],
                    price=item['price'],
                    quantity=item['quantity']
                )
            cart.clear()
            # order_created.delay(order.id)
            # set the order in the session
            request.session['order_id'] = order.id
            # redirect for payment
        return redirect(reverse('payment:process'))
    else:
        form = OrderCreateForm(instance=order)
    return render(request, 'orders/order/create.html', {'cart': cart, 'form': form})


@login_required
def order_list(request, username_id):
    order = None
    orders = Order.objects.all()
    if username_id:
        orders = Order.objects.filter(username_id=username_id)
        return render(request,
                      'orderlist.html',
                      {'orders': orders,
                       'order': order})


@login_required
def order_detail(request, username_id, order_id):
    order = None
    if order_id:
        order = get_object_or_404(Order, id=order_id)
    return render(request,
                  'order_item.html',
                  {'order': order})

orders/templates/order_item.html
{% extends 'cafe/base.html' %}
{% load static %}



{% block title %}
    Order {{ order.id }} {{ block.super }}
{% endblock %}

{% block breadcrumbs %}
    <div class="breadcrumbs">
        <a href="{% url "admin:index" %}">Home</a> &rsaquo;
        <a href="{% url "admin:orders_order_changelist" %}">Orders</a>
        &rsaquo;
        <a href="{% url "admin:orders_order_change" order.id %}">Order {{ order.id }}</a>
        &rsaquo; Detail
    </div>
{% endblock %}

{% block content %}
    <br>
    <br>

    <h4 style="background-color: #5AC8FA" align = "center">Details of your order: {{ order.id }}</h4>
    <ul class="object-tools">
        <li style = "float: right;">
            <a href="#" onclick="window.print();">Print order     </a>
            <br>
        </li>
    </ul>
    <br>
    <table class="table table-striped table-hover">
        <tr>
            <th style="width: 300px">Created</th>
            <td>{{ order.created }}</td>
        </tr>
        <tr>
            <th style="width: 300px">Customer</th>
            <td>{{ order.first_name }} {{ order.last_name }}</td>
        </tr>
        <tr>
            <th style="width: 300px">E-mail</th>
            <td>{{ order.email }}</td>
        </tr>
        <tr>
            <th style="width: 300px">Address</th>
            <td>{{ order.address }}, {{ order.postal_code }} {{ order.city }}</td>
        </tr>
        <tr>
            <th style="width: 300px; height:10px">Total amount         </th>
            <td>${{ order.get_total_cost }}</td>
        </tr>
        <tr>
            <th style="width: 300px; height:20px">Status</th>
            <td>{% if order.paid %}Paid{% else %}Pending payment{% endif %}</td>
        </tr>
    </table>

    <div class="module">
        <h3>What did you order !</h3>
        <div class="tabular">
            <table style="width:100%">
                <thead>
                <tr>
                    <th>Product</th>
                    <th>Price</th>
                    <th>Quantity</th>
                    <th>Total</th>
                </tr>
                </thead>
                <tbody>
                {% for item in order.items.all %}
                    <tr class="row{% cycle "1" "2" %}">
                        <td>{{ item.product.name }}</td>
                        <td class="num">${{ item.price }}</td>
                        <td class="num">{{ item.quantity }}</td>
                        <td class="num">${{ item.get_cost }}</td>
                    </tr>
                {% endfor %}
                <tr class="total">
                    <td colspan="3">Total</td>
                    <td class="num">${{ order.get_total_cost }}</td>
                </tr>
                </tbody>
            </table>

        <br>
        <br>

        <p align = 'center'><b><i>Thanks for shopping with us !</i></b></p>
        </div>
    </div>
{% endblock %}

orders/templates/orderlist.html
{% extends 'cafe/base.html' %}
{% load static %}
{% block title %}
    My Orders
{% endblock %}

{% block content %}
<table class="table table-striped table-hover">
                <thead style="background-color: #5AC8FA">
                    <tr>


    <th> Order ID </th>

    <th> Created Date </th>
                    </tr>
                </thead>
                <tbody>
<tr>



    {% for order in orders %}



<div class="item">

    <td>   <a href="{% url 'orders:order_detail' user.id order.id %}">
        Order No {{ order.id }} </a> </td>

       <td>{{ order.created }} </td>
</tr>
        &#9;
</div>

      {% endfor %}
                </tbody>
</table>
{% endblock %}