cafe/urls.py
from django.urls import path,include
from . import views
from django.conf import settings
from django.conf.urls.static import static
from .views import SignUpView

app_name = 'cafe'

urlpatterns = [
    path('signup/', SignUpView.as_view(), name='signup'),
    path('accounts/', include('django.contrib.auth.urls')),
    path('', views.product_list, name='product_list'),
    path('<slug:category_slug>/', views.menu_list, name='product_list_by_category'),
    path('<slug:category_slug>/', views.product_list, name='product_list_by_category'),
    path('<int:id>/<slug:slug>/', views.product_detail, name='product_detail'),
    path('', views.home, name='home'),

]

cart/urls.py
from django.urls import path, re_path
from . import views

app_name = 'cart'

urlpatterns = [
    re_path(r'^$', views.cart_detail, name='cart_detail'),
    re_path(r'^add/(?P<product_id>\d+)/$', views.cart_add, name='cart_add'),
    re_path(r'^remove/(?P<product_id>\d+)/$', views.cart_remove, name='cart_remove'),
]

orders/urls.py
from django.urls import path
from . import views

app_name = 'orders'

urlpatterns = [
    path('create/', views.order_create, name='order_create'),
    path('admin/order/<int:order_id>/', views.admin_order_detail, name='admin_order_detail'),
    path('admin/order/<int:order_id>/pdf/', views.admin_order_pdf, name='admin_order_pdf'),
    path('myorders/<int:username_id>/', views.order_list, name='myorders'),
    path('myorders/<int:username_id>/<int:order_id>', views.order_detail, name='order_detail'),
]

studentcafe/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('cart', include('cart.urls')),
    path('payment/', include('payment.urls', namespace='payment')),
    path('', include('cafe.urls')),
    path('cafe/', include('django.contrib.auth.urls')),
    path('orders/', include('orders.urls')),
   ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

cafe/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User
from django.urls import reverse
from django.contrib.auth.models import AbstractUser


# Create your models here.

class Category(models.Model):
    name = models.CharField(max_length=100, db_index=True)
    slug = models.SlugField(max_length=150, unique=True, db_index=True)
    category_image = models.ImageField(upload_to='cafe/static/images/categories_image/', null=True, blank=True)

    #    created_date = models.DateTimeField(default=timezone.now)
    #    updated_date = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('cafe:product_list_by_category',
                       args=[self.slug])


class Product(models.Model):
    category =  models.ForeignKey(Category, related_name='products', on_delete=models.CASCADE, null=True)
    name = models.CharField(max_length=100, db_index=True)
    description = models.CharField(max_length=200)
    available_qty = models.PositiveIntegerField()
    available = models.BooleanField(default=True)
    slug = models.SlugField(max_length=150, unique=True, db_index=True)
    price = models.DecimalField(max_digits=10, decimal_places=2)
    image = models.ImageField(upload_to='cafe/static/images/product_image/', null=True, blank=True)
    calories = models.PositiveIntegerField()
    created = models.DateTimeField(default=timezone.now)
    updated = models.DateTimeField(auto_now_add=True)

    def created(self):
        self.created = timezone.now()
        self.save()

    def updated(self):
        self.updated = timezone.now()
        self.save()

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('cafe:product_detail',
                       args=[self.id, self.slug])

class CustomUser(AbstractUser):
    address = models.CharField(max_length=50, blank=True, null=True, default=' ')
    city = models.CharField(max_length=50, default=' ')
    state = models.CharField(max_length=50, default='NE')
    zipcode = models.CharField(max_length=10, default='00000')
    cell_phone = models.CharField(max_length=50, default='(402)000-0000')

cafe/forms.py
from django import forms

from django.contrib.auth.forms import UserCreationForm, UserChangeForm
from .models import CustomUser


class CustomUserCreationForm(UserCreationForm):
    class Meta(UserCreationForm):
        model = CustomUser
        fields = ('username', 'email', 'first_name', 'last_name', 'address', 'city', 'state', 'zipcode', 'cell_phone')
class CustomUserChangeForm(UserChangeForm):
    class Meta:
        model = CustomUser
        fields = ('username', 'email', 'first_name', 'last_name', 'address', 'city', 'state', 'zipcode', 'cell_phone')

cafe/views.py
from django.shortcuts import render, get_object_or_404
from .models import Category, Product
from django.urls import reverse
from cart.forms import CartAddProductForm
from django.core.mail import EmailMessage
from django.urls import reverse_lazy
from django.views import generic
from .forms import CustomUserCreationForm



# Create your views here.
def home(request):
    return render(request, 'cafe/home.html',
                  {'cafe': home})



def product_list(request, category_slug=None):
    category = None
    categories = Category.objects.all()
    products = Product.objects.filter(available=True)
    if category_slug:
        category = get_object_or_404(Category, slug=category_slug)
        products = products.filter(category=category)
    return render(request,
                  'cafe/home.html',
                  {'category': category,
                   'categories': categories,
                   'products': products})


def menu_list(request, category_slug=None):
    category = None
    categories = Category.objects.all()
    products = Product.objects.filter(available=True)
    if category_slug:
        category = get_object_or_404(Category, slug=category_slug)
        products = products.filter(category=category)

    context = {
        'category': category,
        'categories': categories,
        'products': products
    }
    return render(request, 'cafe/product/list.html', context)


def product_detail(request, id, slug):
    product = get_object_or_404(Product, id=id, slug=slug, available=True)
    cart_product_form = CartAddProductForm()
    context = {
        'product': product,
        'cart_product_form': cart_product_form
    }
    return render(request, 'cafe/product/detail.html', context)


class SignUpView(generic.CreateView):
    form_class = CustomUserCreationForm
    success_url = reverse_lazy('login')
    template_name = "registration/signup.html"

cafe/templates/cafe/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">

<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width,
			initial-scale=1, shrink-to-fit=no">
    <link rel="stylesheet" href="{% static 'css/home.css' %}">
     <link rel="stylesheet" href="{% static 'css/login.css' %}">
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
          integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T"
          crossorigin="anonymous">
    <title>Student cafe</title>
</head>
<body>
<!-- Header -->
<header>
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <a class="nav-link" href="{% url 'cafe:home' %}">Menu <span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="#contactus">Contact Us</a>
      </li>
   <!--login functionality-->
        {% if user.is_authenticated %}
            <li class="nav-item"><a class="nav-link" href="{% url 'logout' %}"><i class="fa fa-btn fa-sign-out"></i>Logout</a></li>
        {% else %}
            <li class="nav-item"><a class="nav-link" href="{% url 'login' %}"><span class="glyphicon glyphicon-log-in"></span> Login</a></li>
        {% endif %}

         <!--My bag functionality-->
        <li class="nav-item">
            {% with totail_items=cart|length %}
                {% if cart|length > 0 %}
                    <a class="nav-link" href="{% url "cart:cart_detail" %}" >
                        My bag <sup style="color: firebrick">{{ totail_items }} item{{ totail_items|pluralize }}</sup>
                    </a>
                {% else %}
                    <a class="nav-link" href="{% url "cart:cart_detail" %}">My bag</a>
                {% endif %}
            {% endwith %}
        </li>
     {% if user.is_authenticated %}
        <li class="nav-item">
            <a class="nav-link" href="{% url 'orders:myorders' user.id %}">My Orders</a>
        </li>
    {% else %}
    <li> </li>
    {% endif %}

    </ul>
  </div>
</nav>
<!--
<nav>
    <ul class="nav-flex-row">
        <li class="nav-item">
            <a href="{% url 'cafe:home' %}">Menu</a>
        </li>
        <li class="nav-item">
            <a href="#contact-us">Contact Us</a>
        </li>

        {% if user.is_authenticated %}
            <li><a href="{% url 'logout' %}"><i class="fa fa-btn fa-sign-out"></i>Logout</a></li>
        {% else %}
            <li><a href="{% url 'login' %}"><span class="glyphicon glyphicon-log-in"></span> Login</a></li>
        {% endif %}



        <li class="nav-item">
            <a href="{% url "cart:cart_detail" %}">My bag</a>
            {% with totail_items=cart|length %}
                {% if cart|length > 0 %}

                    <a href="{% url "cart:cart_detail" %}" style="color: firebrick">
                        <sup>{{ totail_items }} item{{ totail_items|pluralize }}</sup>
                    </a>
                {% else %}

                {% endif %}
            {% endwith %}
        </li>
     {% if user.is_authenticated %}
        <li class="nav-item">
            <a href="{% url 'orders:myorders' user.id %}">My Orders</a>
        </li>
    {% else %}
    <li> </li>
    {% endif %}


    </ul>
</nav>
</header>
--!>
<main>
<section class="section-intro">
        <h1>Student's Café</h1>

    {% if user.is_authenticated %}
       <div class="page-container">
           <h4 class="top-menu">Hello {{ user.username }}!</h4>
       </div>
   {% endif %}
</section>

</main>

{% block content %}

{% endblock %}
<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
        integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"
        crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"
        integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1"
        crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"
        integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM"
        crossorigin="anonymous"></script>

</body>
</html>

cafe/templates/cafe/home.html
<!DOCTYPE html>
<html lang="en">
{% extends 'cafe/base.html' %}
{% load static %}
{% block content %}
<body>




<!--Menu container-->
<h3 class="head-categ"><br><u>CATEGORIES</u></h3>
<!--<div class="menu-container">-->
<!--
<div class="category-1">

    <a href="categories1">
            <img src="{% static 'images/categories_image/mains.jpg' %}"
                 class="d-block" height="200px" width="300px" alt="food">
    </a>
    Mains
</div>
</div>


<div class="category-2">
    <a href="categories-beverages-page">
        <img src="{% static 'images/categories_image/beverages.jpg' %}"
             class="d-block" height="200px" width="300px" alt="food">
    </a>
    Beverages
</div>
<div class="category-3">
    <a href="categories-sides-page">
        <img src="{% static 'images/categories_image/sides.jpg' %}"
             class="d-block" height="200px" width="300px" alt="food">

    </a>
    Sides
</div>

</div>
-->

<!--Categories container-->
<div id="main" class="product-list">
          {% for category in categories %}

       {% if category.slug == category.slug %}
            {% endif %}
    <div class="item">
        <a href="{{ category.get_absolute_url }}">
            <img class="img-fluid" src="{% if category.category_image %}{{ category.category_image.url }}{% else %}{% static "images/no_image.png" %}{% endif %}" height="250" width="250">
            &nbsp;
            &#9;


            <a href="{{ category.get_absolute_url }}">{{ category.name }}</a>
            &nbsp;
            &nbsp;

    </div>
          {% endfor %}
&#9;
 &#9;
 &#9;
</div>




<div id="carouselExampleIndicators" class="carousel slide" data-ride="carousel">
  <ol class="carousel-indicators">
    <li data-target="#carouselExampleIndicators" data-slide-to="0" class="active"></li>
    <li data-target="#carouselExampleIndicators" data-slide-to="1"></li>
    <li data-target="#carouselExampleIndicators" data-slide-to="2"></li>
  </ol>
  <div class="carousel-inner">
    <div class="carousel-item active">
      <img class="img-fluid" src="{% static 'images/slider1.jpg' %}" alt="First slide">
    </div>
    <div class="carousel-item">
      <img class="img-fluid" src="{% static 'images/slider2.jpg' %}" alt="Second slide">
    </div>
    <div class="carousel-item">
      <img class="img-fluid" src="{% static 'images/slider3.jpg' %}" alt="Third slide">
    </div>
  </div>
  <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
    <span class="sr-only">Previous</span>
  </a>
  <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
    <span class="carousel-control-next-icon" aria-hidden="true"></span>
    <span class="sr-only">Next</span>
  </a>
</div>





<!--Bottom container-->
<div class="container">
    <div class="row-flex">
        <div class="opening-time">
            <h3>
                Opening times
            </h3>
            <p>
                <span>Monday—Thursday: 08:00 — 22:00</span>
                <span>Friday—Saturday: 09:00 — 23:00 </span>
                <span>Sunday: 10:00 — 17:00</span>
            </p>
        </div>
        <div class="contact-address">
            <h3 id="contactus">
                Contact
            </h3>
            <p>
                <span>010-002-0008</span>
                <span>12 Pine Street</span>
                <span>Omaha 68106, NE</span>
            </p>

        </div>
    </div>
</div>


<!-- Optional JavaScript -->
<!-- jQuery first, then Popper.js, then Bootstrap JS -->

<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
        integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"
        crossorigin="anonymous">
</script>

<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"
        integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1"
        crossorigin="anonymous">
</script>

<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"
        integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM"
        crossorigin="anonymous">
</script>

</body>
{% endblock %}
</html>